data_dir = "/var/lib/vector"

[sources.app_log]
type = "file"
ignore_older_secs = 600
include = [ "/var/app_logs/*.log" ]
read_from = "beginning"

[sinks.parseable]
type = "http"
method = "post"
batch.max_bytes = 10485760
batch.max_events = 1000
batch.timeout_secs = 10
compression = "gzip"
inputs = ["app_log"]
encoding.codec = "json"
uri = 'http://host.docker.internal:8000/api/v1/logstream/demo2'
auth.strategy = "basic"
auth.user = "admin"
auth.password = "admin"
# request.headers.X-P-Stream = "k8slogs"
request.headers.X-P-META-meta1 = 'value1'
request.headers.X-P-TAGS-tag1 = 'value1'
healthcheck.enabled = true
healthcheck.path = 'http://host.docker.internal:8000/api/v1/liveness'
healthcheck.port = 80
